language: bash
services:
  - docker
jobs:
  include:
    - stage: lint chart
      script:
        - docker run --rm -v ${PWD}:/chart -w /chart alpine/helm:3.0.2 lint .
      if: tag is blank
    - stage: publish chart
      script:
        - ./trigger_publish.sh
      if: tag IS present