# Default values for x-arr-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: linuxserver/sonarr
  tag: 3.0.3.741-ls190
  pullPolicy: IfNotPresent
  port: 8989

imagePullSecrets: []
nameOverride: "sonarr"
fullnameOverride: "sonarr"
# where does the container expect the data?
# Sonarr = /tv
# Radarr = /movies
# Lidarr = /music
dataPath: /tv
env:
  TZ: America/Los_Angeles
  PGID: 1000
  PUID: 1000

probes:
  livenessProbe:
    timeoutSeconds: 5
    periodSeconds: 20
    initialDelaySeconds: 60
  readinessProbe:
    timeoutSeconds: 5
    periodSeconds: 20
    initialDelaySeconds: 60

podSecurityContext: {}

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: sonarr.cluster.int
      paths: ['/']
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

# this PV is used for the /config directory, it must exist on the matchHostname
# The pod will only be scheduled to the node which is listed in matchHostname
pv:
  storage: 1Gi
  localPath: /local-pv/sonarr
  matchHostname: k8snode1

nfs:
  server: 192.168.10.131
  path:
    downloads: /data/k8s/downloads
    data: /data/video/Television

resources:
  limits:
    cpu: 250m
    memory: 600Mi
  requests:
    cpu: 50m
    memory: 200Mi
