apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-{{ .Values.nameOverride}}-download
  labels:
    name: pv-nfs-{{ .Values.nameOverride}}-download
spec:
  capacity:
    storage: {{ .Values.downloadStorage }}
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.storageClassName }}
  nfs:
    server: {{ .Values.nfsServerHost}}
    path: {{ .Values.nfsServerPath }}

