apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "x-arr-chart.fullname" . }}
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pv.storage }}