apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "x-arr-chart.fullname" . }}
spec:
  storageClassName: {{ .Values.pvc.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}
