apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "x-arr-chart.fullname" . }}
  labels:
    {{- include "x-arr-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ .Values.nameOverride }}
  selector:
    matchLabels:
      {{- include "x-arr-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "x-arr-chart.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.image.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 60
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /config
            - name: data
              mountPath: {{ .Values.dataPath }}
            - name: downloads
              mountPath: /downloads
      volumes:
        - name: config
          hostPath:
            path: "{{ .Values.localPath }}/{{ .Values.nameOverride }}-config"
        - name: data
          hostPath:
            path: "{{ .Values.localPath }}/{{ .Values.nameOverride }}-data"
        - name: downloads
          hostPath:
            path: "{{ .Values.localPath }}/downloads"
